#!/bin/sh

# (re)create an IPv6 tunnel once connected to certain WLAN networks

# usage:
# - copy to /etc/NetworkManager/dispatcher.d/
# - chown root
# - chmod +x
# - fill HEUSER, HEKEY, HETUNNEL, HESERVER4END, HESERVER6END, HECLIENT6END
#   (see tunnel setting on tunnelbroker.net)


# whitelist of essids
essids=(myhomenetwork, another_network)
interfaces=(wlp3s0)

interface=$1
status=$2
essid=$(/usr/sbin/iwgetid -r)
if [[ ! ${interfaces[*]} =~ $interface ]]; then
    /usr/bin/logger -s "$interface changed to $status - ignoring interface"
    exit 0
fi
if [[ $essid && ! ${essids[*]} =~ $essid ]]; then
    /usr/bin/logger -s "$interface changed to $status - ignoring ESSID=$essid"
    exit 0
fi

IF0='sit0'
IF1='sit1'

case $status in
    up)
        /usr/bin/logger -s "$1 changed to $2 - ESSID=$essid -- (re)starting ipv6 tunnel"

        # tunnelbroker settings..
        HEUSER='...' # tunnelbroker username
        HEKEY='...' # tunnelbroker update key
        HETUNNEL=123 # from the website, "Global Tunnel ID"

        ### other settings from the website (the tunnel settings):
        HESERVER4END='<ipv4 server address>'
        HESERVER6END='<ipv6 server address>'
        HECLIENT6END='<ipv6 client address>'

        if /usr/bin/cat /proc/net/dev | /usr/bin/egrep --quiet "$IF0|$IF1" ; then
            /usr/sbin/route -A inet6 delete ::/0 dev $IF1
            /usr/sbin/ifconfig $IF0 down
            /usr/sbin/ifconfig $IF1 down
        fi

        #echo "Updating your IPv4 tunnel endpoint setting on the Hurricane Electric Website."
        /usr/bin/curl -k -s "https://ipv4.tunnelbroker.net/nic/update?username=$HEUSER&password=$HEKEY&hostname=$HETUNNEL"

        #echo "Setting up the tunnel now."
        /usr/sbin/ifconfig $IF0 up
        /usr/sbin/ifconfig $IF0 inet6 tunnel ::$HESERVER4END

        /usr/sbin/ifconfig $IF1 up
        /usr/sbin/ifconfig $IF1 inet6 add $HECLIENT6END

        /usr/sbin/route -A inet6 add ::/0 dev $IF1

        /usr/bin/logger -s "External IPs are `curl -s 'http://v6.ipv6-test.com/api/myip.php'` and `curl -s 'http://v4.ipv6-test.com/api/myip.php'`"
        ;;
    down)
        /usr/bin/logger -s "$1 changed to $2"

        if /usr/bin/cat /proc/net/dev | /usr/bin/egrep --quiet "$IF0|$IF1" ; then
            /usr/bin/logger -s "removing tunnel"
            /usr/sbin/route -A inet6 delete ::/0 dev $IF1
            /usr/sbin/ifconfig $IF0 down
            /usr/sbin/ifconfig $IF1 down
        fi
        ;;
    *)
        /usr/bin/logger -s "$1 changed to $2"
        ;;
esac
