#!/bin/sh

if [ ! -d "$1" ]
then
	echo "Arg "$1" is NOT a directory!"
	exit 1 
fi

echo "adjusting ogg files"
vorbisgain -a -f -r -s "$1"
echo 

echo "adjusting mp3 files"
#subdirs=$(find "$1" -type d)
#for dir in $subdirs
find "$1" -type d | while read FILE
do
	dir=$FILE
	mp3count=`ls "$dir"/*.mp3 2>/dev/null | wc -l`
	if [ $mp3count -lt 1 ]
	then
		echo "skipping $dir"
	else
		mp3gain -p "$dir"/*.mp3
	fi
done

echo "done"

