#!/bin/sh

# inve
#
# usage: inve [COMMAND [ARGS]]
#
# For use with Ian Bicking's virtualenv tool. Attempts to find the root of
# a virtual environment. Then, executes COMMAND with ARGS in the context of
# the activated environment. If no COMMAND is given, activate defaults to a
# subshell.

start="$PWD"

# First, locate the root of the current virtualenv
while [ "$PWD" != "/" ]; do
    if [ -x bin/python ]; then
        # we're alreay in a directory containing a (executable) bin/python
        break
    fi

    # dotglob -> "*" also matches names starting with "."
    shopt -s dotglob
    # nullglob -> no result if pattern doesn't match
    shopt -s nullglob
    PYs=(*/bin/python)
    shopt -u dotglob
    shopt -u nullglob

    # strip "/bin/python" off the end of each match
    PYs=(${PYs[@]//\/bin\/python/})

    if [ "${#PYs[@]}" -eq "1" ]; then
        # one match -> use it!
        cd ${PYs[0]}
        break
    elif [ ${#PYs[@]} -ge 2 ]; then
        # multiple matches -> ask the user
        PS3="Multiple environments found - please choose: "
        select PY in ${PYs[@]}; do
            if [ ! -z "$PY" ]; then
                cd $PY
                break
            else
                echo " > invalid choice!"
            fi
        done
        break
    fi

    cd ..
done

if [ "$PWD" = "/" ]; then
    cd "$start"
    echo "Could not activate: no virtual environment found." >&2
    exit 1
fi

venv="$PWD"
cd "$start"

# Activate
export VIRTUAL_ENV="$venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"
unset PYTHON_HOME
exec "${@:-$SHELL}"
