#!/bin/sh

# inve
#
# usage: inve [COMMAND [ARGS]]
#
# For use with Ian Bicking's virtualenv tool. Attempts to find the root of
# a virtual environment. Then, executes COMMAND with ARGS in the context of
# the activated environment. If no COMMAND is given, activate defaults to a
# subshell.

start="$PWD"

# First, locate the root of the current virtualenv
while [ "$PWD" != "/" ]; do
    # Stop here if this the root of a virtualenv
    if [ \
        -x bin/python \
        -a -d lib/python*/site-packages ]
    then
        break
    elif [ -d .venv/bin \
           -a -x .venv/bin/python \
           -a -d .venv/lib/python*/site-packages ]
    then
        cd .venv
        break
    fi
    cd ..
done
if [ "$PWD" = "/" ]; then
    cd "$start"
    echo "Could not activate: no virtual environment found." >&2
    exit 1
fi

venv="$PWD"
cd "$start"

# Activate
export VIRTUAL_ENV="$venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"
unset PYTHON_HOME
exec "${@:-$SHELL}"
