#!/bin/sh

BASE=$(pwd)

find . -type f -name .ytdlsource | while read SOURCE
do
    SOURCE=${SOURCE/\./$BASE}
    cd "$(dirname "$SOURCE")"
    pwd
    youtube-dl -f m4a -t -i -c -w -x -a .ytdlsource
done

