#!/bin/sh

BASE=$(pwd)

find . -type f -name .ytdlsource | while read SOURCE
do
    SOURCE=${SOURCE/\./$BASE}
    pushd "$(dirname "$SOURCE")" > /dev/null
    pwd
    youtube-dl -t -i -c -w -x -a .ytdlsource
    popd > /dev/null
done

