#!/bin/sh

pwd

shopt -s nocaseglob
for FILE in *.mov
do
    DEST=$(echo $FILE | sed 's/\.mov/\.mp4/I')
    echo "----- $FILE -> $DEST -----"

    ffmpeg -i "$FILE" -vcodec libx264 -crf 26 -strict -2 "$DEST" || break
    touch -r "$FILE" "$DEST"
done

for FILE in *.avi
do
    DEST=$(echo $FILE | sed 's/\.avi/\.mp4/I')
    echo "----- $FILE -> $DEST -----"

    ffmpeg -i "$FILE" -vcodec libx264 -crf 26 -strict -2 "$DEST" || break
    touch -r "$FILE" "$DEST"
done
shopt -u nocaseglob
