set lines=44 columns=120
set ve=all

set guioptions-=m " no menu
set guioptions-=T " no toolbar
set guioptions-=r " no right scrollbar

if has('win32')
    " set guifont=Consolas:h10:cANSI
    set guifont=Sauce_Code_Powerline_PNFT_Mono_:h9:cANSI
else
    " set guifont=Hack\ 10
    set guifont=ProFontWindows\ Nerd\ Font\ 12
endif

" colorscheme summerfruit256
highlight Normal guifg=gray guibg=black
