"-------------------------------------------------------------------------------
" Automatic reloading of .vimrc
"-------------------------------------------------------------------------------
augroup reload_vimrc
    au!
    au bufwritepost $MYVIMRC nested source $MYVIMRC
augroup END
"-------------------------------------------------------------------------------
" Plugins
"-------------------------------------------------------------------------------
if has('win32')
    let plug_path='$HOME/vimfiles/plugged'
else
    let plug_path='$HOME/.vim/plugged'
endif
call plug#begin(plug_path)

" git
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'

" svn (sigh)
Plug 'vim-scripts/vim-svngutter'

" distraction free
Plug 'junegunn/goyo.vim', {'on': 'Goyo'}

" nerdtree (+git)
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" unite, unite-outline
Plug 'Shougo/vimproc.vim'
Plug 'Shougo/unite.vim'
Plug 'Shougo/unite-outline'

" fileencodings & language plugins
Plug 's3rvac/AutoFenc'
Plug 'NLKNguyen/c-syntax.vim', {'for': 'c'}
Plug 'chrisbra/csv.vim', {'for': 'csv'}
Plug 'wannesm/wmgraphviz.vim', {'for': ['dot', 'gv']}
Plug 'jimenezrick/vimerl', {'for': 'erlang'}
Plug 'fatih/vim-go', {'for': 'go'}
Plug 'pangloss/vim-javascript', {'for': 'javascript'}
Plug 'elzr/vim-json', {'for': 'json'}
Plug 'tpope/vim-markdown', {'for': 'markdown'}
Plug 'zah/nim.vim', {'for': 'nim'}
Plug 'hdima/python-syntax', {'for': 'python'}
Plug 'Rykka/riv.vim', {'for': 'rst'}
Plug 'rust-lang/rust.vim', {'for': 'rust'}
Plug 'lervag/vimtex', {'for': 'tex'}

" fold, complete, buffers, search
Plug 'tmhedberg/SimpylFold'
Plug 'ervandew/supertab'

" syntax check..
Plug 'scrooloose/syntastic'
Plug 'nvie/vim-flake8', {'for': 'python'}

" scheme: molokai
Plug 'tomasr/molokai'
" scheme: solarized
Plug 'altercation/vim-colors-solarized'
" scheme: summerfruit256
Plug 'vim-scripts/summerfruit256.vim'
" scheme: wombat256mod
Plug 'vim-scripts/wombat256.vim'
" scheme: wombat256i
Plug 'dsolstad/vim-wombat256i'
" scheme: apprentice
Plug 'romainl/Apprentice'
" scheme: PaperColor
Plug 'NLKNguyen/papercolor-theme'

" bufferline, lightline, icons
Plug 'bling/vim-bufferline'
Plug 'itchyny/lightline.vim'
Plug 'ryanoasis/vim-devicons'

call plug#end()
"-------------------------------------------------------------------------------
" Set encoding to utf-8
"-------------------------------------------------------------------------------
set encoding=utf-8
"-------------------------------------------------------------------------------
" Toggle paste - turns on/off autoindenting etc.
"-------------------------------------------------------------------------------
set pastetoggle=<F2>
"-------------------------------------------------------------------------------
" Turn off paste mode when leaving insert
"-------------------------------------------------------------------------------
au InsertLeave * set nopaste
"-------------------------------------------------------------------------------
" Select a default copy&paste register
" * is selection ~ unnamed
" + is clipboard ~ unnamedplus
"-------------------------------------------------------------------------------
if has("win32")
    set clipboard=unnamed
else
    set clipboard=unnamedplus
endif
"-------------------------------------------------------------------------------
" Mouse & Backspace
"-------------------------------------------------------------------------------
set mouse=a
set bs=2
"-------------------------------------------------------------------------------
" Brackets & scrolling
"-------------------------------------------------------------------------------
set sm " Shortly jump to matching bracket
set so=4 " scrolloff (lines of context during scrolling)
"-------------------------------------------------------------------------------
" <Leader> key
"-------------------------------------------------------------------------------
let mapleader=","
"-------------------------------------------------------------------------------
" Learn to move..
"-------------------------------------------------------------------------------
nnoremap <Left> :echoe "Use h"<CR>
vnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
vnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
vnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>
vnoremap <Down> :echoe "Use j"<CR>
"-------------------------------------------------------------------------------
" faster split resize
"-------------------------------------------------------------------------------
map <Leader>+ <esc>:vertical resize +5<CR>
map <Leader>- <esc>:vertical resize -5<CR>
"-------------------------------------------------------------------------------
" new split below/right of current
"-------------------------------------------------------------------------------
set splitbelow
set splitright
"-------------------------------------------------------------------------------
" move between splits
"-------------------------------------------------------------------------------
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
"-------------------------------------------------------------------------------
" easier buffer switching
"-------------------------------------------------------------------------------
map <Leader>n <esc>:bprevious<CR>
map <Leader>m <esc>:bnext<CR>
"-------------------------------------------------------------------------------
" open new (empty) buffer
"-------------------------------------------------------------------------------
map <Leader>a <esc>:enew<CR>
"-------------------------------------------------------------------------------
" open new vertical split
"-------------------------------------------------------------------------------
map <Leader>v <esc>:vnew<CR>
"-------------------------------------------------------------------------------
" close current file, but keep buffers intact
"-------------------------------------------------------------------------------
map <Leader>x <esc>:bp\|bd #<CR>
"-------------------------------------------------------------------------------
" change directory to that of current file
"-------------------------------------------------------------------------------
map <Leader>cd :cd %:p:h<CR>
"-------------------------------------------------------------------------------
" map sort to a key
"-------------------------------------------------------------------------------
vnoremap <Leader>s :sort<CR>
"-------------------------------------------------------------------------------
" easier moving of code blocks
"-------------------------------------------------------------------------------
vnoremap < <gv
vnoremap > >gv
"-------------------------------------------------------------------------------
" Make search case insensitive
"-------------------------------------------------------------------------------
set hlsearch
set incsearch
set ignorecase
set smartcase
"-------------------------------------------------------------------------------
" Automatically insert \v when searching, for sensible regex matching.
"-------------------------------------------------------------------------------
nnoremap <M-/> \v
vnoremap <M-/> /\v
nnoremap <M-?> ?\v
vnoremap <M-?> ?\v
" nnoremap / /\v
" vnoremap / /\v
" nnoremap ? ?\v
" vnoremap ? ?\v
"-------------------------------------------------------------------------------
" Keep search matches in the middle of the screen, and pulse the line when moving
"-------------------------------------------------------------------------------
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz
nnoremap <silent> g# g#zz
"-------------------------------------------------------------------------------
" Clear search highlight
"-------------------------------------------------------------------------------
noremap <silent> <C-n> :nohl<CR>
vnoremap <silent> <C-n> :nohl<CR>
inoremap <silent> <C-n> <esc>:nohl<CR>
"-------------------------------------------------------------------------------
" Highlight multiple spaces and trailing whitespace
"-------------------------------------------------------------------------------
set listchars=tab:\|\ ,trail:·
set list
highlight Whitespace cterm=underline gui=underline ctermfg=yellow guifg=yellow
au ColorScheme * highlight Whitespace cterm=underline gui=underline ctermfg=yellow guifg=yellow
au BufWinEnter * call matchadd('Whitespace', '  \+\($\)\@!', -1)
" highlight trailing whitespace
au BufWinEnter * call matchadd('ErrorMsg', '\s\+$', -1)
"-------------------------------------------------------------------------------
" Set color scheme
"-------------------------------------------------------------------------------
if !has('gui_running')
    set t_Co=256
endif
set background=dark
" colorscheme apprentice
" colorscheme wombat256i
colorscheme PaperColor
" set background=light
" colorscheme summerfruit256
call togglebg#map("<F4>")
"-------------------------------------------------------------------------------
" Enable syntax highlighting
"-------------------------------------------------------------------------------
filetype off
filetype plugin indent on
syntax on
"-------------------------------------------------------------------------------
" (relative) line numbers
"-------------------------------------------------------------------------------
au InsertEnter * set number norelativenumber
au InsertLeave * set number relativenumber
set number relativenumber
"-------------------------------------------------------------------------------
" 80 cols, wrap, ..
"-------------------------------------------------------------------------------
set tw=80
set wrap
set linebreak
set fo-=t
set colorcolumn=+1
highlight ColorColumn ctermbg=236
"-------------------------------------------------------------------------------
" Useful settings
"-------------------------------------------------------------------------------
set history=1000
set undolevels=1000
"-------------------------------------------------------------------------------
" Don't use TABs but 4 spaces (except for xml, see below..)
"-------------------------------------------------------------------------------
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
"-------------------------------------------------------------------------------
" Indent new lines
"-------------------------------------------------------------------------------
set autoindent
"-------------------------------------------------------------------------------
" Disable stupid backup and swap files - they trigger too many events
" for file system watchers
"-------------------------------------------------------------------------------
set nobackup
set nowritebackup
set noswapfile
"-------------------------------------------------------------------------------
" Filetype mappings..
"-------------------------------------------------------------------------------
au BufNewFile,BufRead *.md set filetype=markdown
au BufNewFile,BufRead *.config set filetype=xml
au BufNewFile,BufRead *.conf set filetype=config
au BufNewFile,BufRead *.geojson set filetype=json
"-------------------------------------------------------------------------------
" Virtualenv support
"-------------------------------------------------------------------------------
" py << EOF
" import os
" import sys
" if 'VIRTUAL_ENV' in os.environ:
"   project_base_dir = os.environ['VIRTUAL_ENV']
"   activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
"   execfile(activate_this, dict(__file__=activate_this))
" EOF
"-------------------------------------------------------------------------------
" Folding..
"-------------------------------------------------------------------------------
nnoremap <Leader>f za
vnoremap <Leader>f zf
au FileType python setl fen foldmethod=indent foldlevelstart=0 foldnestmax=3
au FileType json,c,cpp setl fen foldmethod=syntax foldlevelstart=2
" slow for big files..
" let g:xml_syntax_folding=1
" au FileType xml setl fen foldmethod=syntax foldlevelstart=1
au FileType xml setl fen foldmethod=indent foldlevelstart=1 sw=2
"-------------------------------------------------------------------------------
" lightline
"-------------------------------------------------------------------------------
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename' ],
      \             [ 'bufferline' ] ],
      \   'right': [ [ 'lineinfo' ], [ 'percent'],
      \              [ 'fileformat', 'fileencoding', 'filetype', 'syntastic' ] ]
      \ },
      \ 'component': {
      \   'bufferline': '%{bufferline#refresh_status()}%{g:bufferline_status_info.before . g:bufferline_status_info.current . g:bufferline_status_info.after}'
      \ },
      \ 'component_expand': {
      \     'syntastic': 'SyntasticStatuslineFlag',
      \ },
      \ 'component_type': {
      \     'syntastic': 'middle',
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightLineFugitive',
      \   'readonly': 'LightLineReadonly',
      \   'modified': 'LightLineModified',
      \   'filename': 'LightLineFilename',
      \   'filetype': 'LightLineTypeIcon',
      \   'fileformat': 'LightLineFormatIcon'
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '', 'right': '' }
      \ }

function! LightLineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightLineReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return ""
  else
    return ""
  endif
endfunction

function! LightLineFugitive()
  if exists("*fugitive#head")
    let _ = fugitive#head()
    return strlen(_) ? ' '._ : ''
  endif
  return ''
endfunction

function! LightLineFilename()
  return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction

function! LightLineTypeIcon()
    return winwidth(0) < 70 ? '' : (strlen(&filetype) ? &filetype . ' ' .
                \ WebDevIconsGetFileTypeSymbol() : 'no ft')
endfunction

function! LightLineFormatIcon()
    return winwidth(0) < 70 ? '' : (&fileformat . ' ' .
                \ WebDevIconsGetFileFormatSymbol())
endfunction

set laststatus=2
set noshowmode
"-------------------------------------------------------------------------------
" silence bufferline - lightline will display its content
"-------------------------------------------------------------------------------
let g:bufferline_echo=0
"-------------------------------------------------------------------------------
" running stuff ~> format/lint/whatever/..
"-------------------------------------------------------------------------------
au FileType json map <buffer> <F3> :%!python -m json.tool<CR>
au FileType nim map <buffer> <Leader>c :!nim c %<CR>
au FileType nim map <buffer> <F3> :!nim c -r %<CR>
au FileType python map <buffer> <F3> :call Flake8()<CR>
au FileType xml map <buffer> <F3> :%!xmllint --format --recover -<CR>
au FileType html map <buffer> <F3> :!tidy -q -mi --show-errors 0 --wrap 0 %<CR>
nnoremap <F5> :!make<CR>
"-------------------------------------------------------------------------------
" goyo.vim
"-------------------------------------------------------------------------------
nnoremap <Leader><Space> :Goyo<CR>
let g:goyo_width = 120
let g:goyo_linenr = 0
" "-------------------------------------------------------------------------------
" " Tagbar
" "-------------------------------------------------------------------------------
" nmap <F8> :TagbarToggle<CR>
"-------------------------------------------------------------------------------
" Tagbar for objective c
"-------------------------------------------------------------------------------
let g:tagbar_type_objc = {
    \  'ctagstype': 'objc'
    \, 'ctagsargs': [
    \   '--options='.expand('~/.vim/extras/ctags-options-objc')
    \,  '--objc-kinds=-N'
    \,  '--format=2'
    \,  '--excmd=pattern'
    \,  '--extra='
    \,  '--fields=nksaSmte'
    \,  '-f -'
    \]
    \, 'kinds': [
    \     'i:class interface'
    \,    'x:class extension'
    \,    'I:class implementation'
    \,    'P:protocol'
    \,    'M:method'
    \,    't:typedef'
    \,    'v:variable'
    \,    'p:property'
    \,    'e:enumeration'
    \,    'f:function'
    \,    'd:macro'
    \,    'g:pragma'
    \,    'c:constant'
    \, ]
    \, 'sro': ' '
    \}
"-------------------------------------------------------------------------------
" Syntastic
"-------------------------------------------------------------------------------
let g:syntastic_python_python_exec = '~/opt/bin/python3'
"-------------------------------------------------------------------------------
" NERDTree
"-------------------------------------------------------------------------------
map <Leader>e :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.pyc$', '\~$', '^__pycache__$']
"-------------------------------------------------------------------------------
" NERDTree GitPlugin & WebDevIcons
"-------------------------------------------------------------------------------
let g:WebDevIconsNerdTreeGitPluginForceVAlign=1
"-------------------------------------------------------------------------------
" git fugitive
"-------------------------------------------------------------------------------
autocmd BufReadPost fugitive://* set bufhidden=delete " Delete all fugitive buffers except this
"-------------------------------------------------------------------------------
" Unite
"-------------------------------------------------------------------------------
map <Leader>b :Unite buffer<CR>
map <Leader>r :Unite file_rec<CR>
nmap <F8> :Unite -buffer-name=outline outline<CR>
nnoremap <Leader>/ :Unite grep:.<CR>
" Useful when building interfaces at appropriate places
let g:unite_source_menu_menus = {}
" Interface for Git
let g:unite_source_menu_menus.git = {
   \ 'description' : 'Fugitive interface',
   \}
let g:unite_source_menu_menus.git.command_candidates = [
   \[' git status', 'Gstatus'],
   \[' git diff', 'Gvdiff'],
   \[' git commit', 'Gcommit'],
   \[' git stage/add', 'Gwrite'],
   \[' git checkout', 'Gread'],
   \[' git rm', 'Gremove'],
   \[' git cd', 'Gcd'],
   \[' git push', 'exe "Git! push -u origin " input("branch: ")'],
   \[' git pull', 'exe "Git! pull " input("branch: ")'],
   \[' git fetch', 'Gfetch'],
   \[' git merge', 'Gmerge'],
   \[' git browse', 'Gbrowse'],
   \[' git head', 'Gedit HEAD^'],
   \[' git parent', 'edit %:h'],
   \[' git log commit buffers', 'Glog --'],
   \[' git log current file', 'Glog -- %'],
   \[' git log last n commits', 'exe "Glog -" input("num: ")'],
   \[' git log first n commits', 'exe "Glog --reverse -" input("num: ")'],
   \[' git log until date', 'exe "Glog --until=" input("day: ")'],
   \[' git log grep commits',  'exe "Glog --grep= " input("string: ")'],
   \[' git log pickaxe',  'exe "Glog -S" input("string: ")'],
   \[' git index', 'exe "Gedit " input("branchname\:filename: ")'],
   \[' git mv', 'exe "Gmove " input("destination: ")'],
   \[' git grep',  'exe "Ggrep " input("string: ")'],
   \[' git prompt', 'exe "Git! " input("command: ")'],
   \] " Append ' --' after log to get commit info commit buffers
nnoremap <silent> <Leader>g :Unite -direction=botright -silent -buffer-name=git menu:git<CR>
